# This is a Jekyll configoration file for Github Pages
title: BoxCritters Private Box
url: https://boxcritters.github.io/private-box
server-url: https://bcmc-private-box.herokuapp.com

pb-plugins:


permalink: pretty
production: true

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  auto_ids: false


excludes:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - "*.sh"
  - "*.bat"
  - README.md
  - package.json
  - ".gitignore"
  - CNAME
  - server
  - build
  - index.js